enovance/openstack-yaml-infra

data/common.yaml.tmpl
data/type.yaml.tmpl
scenarios/2nodes/infra.yaml
scenarios/3ctrl_3networker_Xcpt_cephless/infra.yaml
scenarios/3ctrl_xcpt/infra.yaml
scenarios/3nodes/infra.yaml
scenarios/3nodes_cephless/infra.yaml
scenarios/ref-arch-packed/infra.yaml
scenarios/ref-arch/infra.yaml

In order for puppet-openstack-cloud to be installed in a masterless way
every node needs to have their puppetdb conf properly set. This is what
this commit allow.

Configure PuppetDB on each node

---

data/common.yaml.tmpl
data/type.yaml.tmpl

Add lookups for new logging::server parameters needed by the
haproxy member resource to allow HA in logging infrastructure.

Add lookup for logging::server parameters

---

scenarios/ref-arch/infra.yaml

I don't really understand why the arity is set to 3+2n. I understand
that 3 is now the standard factor of replication but I don't understand
why it's not possible to have let say 6 storage nodes :)

Update the arity of storage from 3+2n to 3+1n for ref-arch

---

data/common.yaml.tmpl

Reflect this commit :
https://github.com/enovance/puppet-openstack-cloud/pull/682

Reflect the change on puppet-ceph (specify a journal device by osd)

---

data/common.yaml.tmpl

This commit aims to let a deployer to allow more than
one allowed_host in Horizon.

common: Allow more horizon_allowed_hosts

---

data/common.yaml.tmpl
data/type.yaml.tmpl
scenarios/2nodes/infra.yaml
scenarios/3ctrl_3networker_Xcpt_cephless/infra.yaml
scenarios/3ctrl_xcpt/infra.yaml
scenarios/3nodes/infra.yaml
scenarios/3nodes_cephless/infra.yaml
scenarios/ref-arch-packed/infra.yaml
scenarios/ref-arch/infra.yaml

This commit aims to instantiate Redis sentinel on each controller
node. This  way the Redis can work as a cluster and provide failover.

infra: Enable Redis sentinel on controller nodes

---

data/common.yaml.tmpl

If galera is not bind on internal network then the mysqlchk service still bind
on it because we can't override the value of galera_clustercheck_ipaddress in
the env yaml file.
The haproxy galera backend expects to have port 3306 and 8200 on the same
network.

common: Allow binding of mysqlchk

---

scenarios/ref-arch/infra.yaml

The pool setup should be executed on controller and not on the storage nodes.

Moving the pool setup on controller

---

data/common.yaml.tmpl

Currently, the default behaviour is for the services to use the
publicURL endpoint, but in the majority of cases, we'll prefer to have
the services use the internalURL endpoint instead (because mainly of
network segmentation).

Services should use the internalURL endpoint

---

data/common.yaml.tmpl

In J-1.1.0, we used to install a version of the MongoDB package that was
reading its configuration from /etc/mongodb.conf, with the newer version
of the package the conf is read from /etc/mongod.conf

Specify path to MongoDB configuration

---

data/type.yaml.tmpl

The idea is to enable something like the following:
infra: ref-arch
profiles:
...
compute:
config:
nova::scheduler::filter::ram_allocation_ratio: 4
nova::scheduler::filter::cpu_allocation_ratio: 16
...
hosts:
....

data/type.yaml: Make it possible to set per-profile/type extra hiera config

---

scenarios/2nodes/infra.yaml
scenarios/3ctrl_3networker_Xcpt_cephless/infra.yaml
scenarios/3ctrl_xcpt/infra.yaml
scenarios/3nodes/infra.yaml
scenarios/3nodes_cephless/infra.yaml
scenarios/ref-arch-packed/infra.yaml
scenarios/ref-arch/infra.yaml

The install-server profile runs base serverspec test :
https://github.com/enovance/openstack-serverspec/blob/master/spec/tests/base/base_spec.rb#L12-L14
But the variable vip_public is not set on this profile like on compute, etc..
```
install-server:
/usr/bin/ruby -S rspec spec/base/base_spec.rb spec/puppetdb_server/puppetdb_server_spec.rb spec/redis_server/redis_server_spec.rb -t ~host:install-server.domain.org
Run options: exclude {:host=>"install-server.domain.org"}
.........
Top 9 slowest examples (0.17653 seconds, 100.0% of total time):
Command "timeout 1 dig " should return exit status 0
0.0402 seconds ./spec/tests/base/base_spec.rb:13
```
And the command should be :
```
Command "timeout 1 dig os.domain.org" should return exit status 0
```

infra.yml: Missing spec param on IS

---

scenarios/ref-arch-packed/infra.yaml

Backport fix from master
(cherry picked from commit e1bcd8b8f9124243bb6706e5777dee255b5faefc)

ref-arch-packed: role controller should be lb-controller J.1.1

---

scenarios/ref-arch-packed/infra.yaml

Backport fix from master
(cherry picked from commit e1bcd8b8f9124243bb6706e5777dee255b5faefc)

ref-arch-packed: role controller should be lb-controller J.1.0

---

scenarios/3ctrl_xcpt_splitted-storage/infra.yaml

Fix typo in infra name.
```
Incoherent infra(3ctrl-xcpt-splitted-storage) and env(3ctrl_xcpt_splitted-storage)
```

fix typo in 3ctrl_xcpt_splitted-storage scenario

---

scenarios/3ctrl_xcpt_splitted-storage/infra.yaml

Fix typo in infra name.
```
Incoherent infra(3ctrl-xcpt-splitted-storage) and env(3ctrl_xcpt_splitted-storage)
```

fix typo in 3ctrl_xcpt_splitted-storage scenario (like #52)

---

data/common.yaml.tmpl

By default, ceph_public_network use public_network. If storage node doesn't access to public_network, I need to overload this param.
Thanks to @goldyfruit and @nhicher

data/common.yaml.tmpl: permit to overload ceph_public_network

---

data/common.yaml.tmpl

When using a cinder backend with parameters requiring an array value we have a
malformed common yaml file because we have multiple simple quotes.
This patch forces the simple quotes only if the value is a string.
Close #58

common.yaml: Fix array value for Cinder backend.

---

data/common.yaml.tmpl

Since J.1.2.0 (RHEL updated to 7.1) the package version of mongodb
is now 2.6.9-1.el7.
If we don't set the value of mongodb_version puppet will try to downgrade
the mongodb packages to 2.6.5-2.el7ost.

common.yaml.tmpl: Fix mongodb default version

---

data/common.yaml.tmpl

Since https is fully supported for nova metadata we don't need anymore to
set http as default value for nova_metadata_proto.
We can now use by default the value defined in endpoint_public_protocol.

common.yaml.tmpl: Use endpoint_public_protocol for nova_metadata_proto

---

data/type.yaml.tmpl

https://review.openstack.org/#/c/190464/ introduced a new parameter for
nova::vncproxy with a default value set to http.
To be able to configure vncproxy with https we need to add also a new
parameter in cloud::compute::consoleproxy

type.yaml.tmpl: Fix nova vncproxy protocol

---

data/type.yaml.tmpl

The commit 856f1c8ca06108992f1d3c22106f1d26a5b5b93a was not enough to
configure novnc_base_url depending on the architure of controller/compute
nodes.
With this patch we are sure to have the same configuration on controller and
compute and not depending on nova::compute and nova::vncproxy parameters.

type.yaml.tmpl: Fix nova vncproxy params
